package com.davidsalas.reservations.model.enums;

public enum ErrorCodeEnum {
    DATE_ALREADY_RESERVED,
    INVALID_RESERVATION_DATE_RANGE,
    RESERVATION_NOT_FOUND,
    INVALID_RESERVATION_STAY_TIME,
    INVALID_RESERVATION_ANTICIPATION,
    INVALID_REQUEST_PARAMETER,
    RESERVATION_ALREADY_CANCELLED,
    UNEXPECTED_EXCEPTION
}
