spring:
  datasource:
    url: 'jdbc:h2:mem:Volcano_Island_Reservations'
    username: 'sa'
    password: 'Password01'
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true